# Lecture 12.1
Defining our own functions

In [1]:
def triple(number):                   #define the function, name it 'triple', set a parameter, :
    return 3*number                   #return what we want the computer to do (e.g., a formula)

In [2]:
triple(7)                             #now we can use our function!

21

In [3]:
triple(200)                           #test it with different numbers

600

In [4]:
triple(-200)                          #try any numbers you want! Hooray, it works! 

-600

In [5]:
def triple(x):                        #it's common to just refer to parameters as 'x'
    return 3*x                        #now it looks more like a mathematical expression

In [6]:
triple(4)                             #now we have a function we can re-use (within this notebook)!

12

In [7]:
def triple(x):                        #a good practice can be to describe your function in comments like here
    'triple the value of x'           #but you can also write it this way
    return 3*x 

In [8]:
triple(75)                            #sweet

225

In [9]:
def far_to_cel(x):                    #this is actually very useful for my American-centric brain!!
    return ((x-32)*(5/9))             #this is the formula to convert fahrenheit to celsius

In [10]:
far_to_cel(100)

37.77777777777778

In [11]:
def far_to_cel_2(x):                                   #let's try a slightly different version  
    'this converts a temperature value from F to C'    #labeling this time
    return (x-32)*(5/9)                                #we have removed the surrounding () and it still works

In [12]:
far_to_cel_2(100)

37.77777777777778

In [13]:
def triple(x):                         #let's confirm it works with parenthesis in our original example
    return (3*x)                       #adding ()

In [14]:
triple(8)                              #cool!

24

In [15]:
def ___(__):                             #try your own! Name it anything you like!
    'Try your own'                       #describe it if you like
    return(__)                           #make it do anything you like!

In [16]:
def percentage(x, y):                    #we can create functions with more than one parameter
    'Find what percent x is of y'
    return ((x/y)*100)

In [17]:
percentage(10, 100)                      #test it with an easy one

10.0

In [18]:
percentage(28, 30)                       #now we have something (vaguely) useful!

93.33333333333333

# Lecture 12.2
Loops

In [19]:
mylist = [1, 2, 3, 4]                  #create a list
for i in mylist:                       #for every value in my list
    print(i)                           #print that value!

1
2
3
4


In [20]:
mylist = [1, 2, 3, 4]                  
for x in mylist:                       #it doesn't have to be i
    print(x)   

1
2
3
4


In [21]:
prices = [2, 4, 6, 8]                 #we can call our sequence whatever we like, as always
for x in prices: 
    print(x)

2
4
6
8


In [22]:
import numpy as np                  #we can iterate over a numpy array, too
myarray = np.array([3, 5, 7, 9])

for x in myarray:
    print(x)

3
5
7
9


In [23]:
type(myarray)                       #confirm, indeed, we created an array!

numpy.ndarray

In [24]:
for i in range(10):                #if we just give one number in range(), it becomes the endpoint
     print(i)

0
1
2
3
4
5
6
7
8
9


In [25]:
for i in range(11):                #the endpoint is not inclusive
    print(i)

0
1
2
3
4
5
6
7
8
9
10


In [26]:
for i in range(2, 10):            #with two numbers specified it goes (beginning, end)
    print(i)

2
3
4
5
6
7
8
9


In [27]:
for i in range(2, 10, 2):        #with three numbers specified it goes (beginning, end, interval)
    print(i)

2
4
6
8


In [28]:
myrange = np.arange(5, 20, 2)       #we can make a range stand alone using numpy (it creates an array)
myrange

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
type(myrange)                        #checking that it's an array

numpy.ndarray

In [30]:
np.arange(5, 20)                     #again, specfifying two numbers means (start, end)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [31]:
np.arange(20)                        #specifying just one makes it the endpoint

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [32]:
x = 0                               #while loops!
while x<10:
    print(x)
    x = x+1

0
1
2
3
4
5
6
7
8
9


In [33]:
x = 5                              #experiment with different values for x and see what happens
while (x<10):
    print(x)
    x = x+1

5
6
7
8
9


In [34]:
x = 0                               #experiment with the condition for the while loop
while (x<=10):
    print(x)
    x = x+1

0
1
2
3
4
5
6
7
8
9
10


In [35]:
x = 0                                #keep experimenting with the condition
while (x==10):
    print(x)
    x = x+1

In [36]:
x = 0                                #experimenting
while (x==0):
    print(x)
    x = x+1

0


In [37]:
x = 0                                 #we can give slightly more complicated instructions
while (x<5):
    print('The value of x is', x)
    x = x+1
print('The end')

The value of x is 0
The value of x is 1
The value of x is 2
The value of x is 3
The value of x is 4
The end


In [38]:
for i in range(1, 10):               #we can write nested loops!
    for j in range (1, 2):
        print(i+j)

2
3
4
5
6
7
8
9
10


In [39]:
#x=0                                 #this is an infinite loop! Try it! 
#while x<10:                         #see how long you can take it before hitting stop (haha)
#    print(x)

In [40]:
#x = 1                               #another infinite loop!
#while x>0:
#    print(x)
#    x = x+1

In [41]:
i = 2                                    #don't worry about knowing what every exact step does
while(i < 10):                           #this is just an example of a more complicated use of loops
    j = 2                                #including nested loops and break 
    while(j <= (i/j)):
        if not(i%j): break
        j = j+1
    if (j > i/j): print(i, 'is prime')
    i = i+1
print('Bye!')

2 is prime
3 is prime
5 is prime
7 is prime
Bye!


# Lecture 12.3
Conditional statements

In [42]:
x = 5                                #if statement!
if x > 4:
    print(x)

5


In [43]:
x = 5                                #experimenting!
if x > 5:
    print(x)

In [44]:
x = 5                                #slightly more complicated output 
if x > 0:
    print(x, 'is positive')

5 is positive


In [45]:
x = 5                                #if else!
if x > 0:
    print(x, 'is positive')
else:
    print(x, 'is negative')

5 is positive


In [46]:
x = -5                                #experimenting with different values of x
if x > 0:
    print(x, 'is positive')
else:
    print(x, 'is negative')

-5 is negative


In [47]:
x = 5                                #if elif else!
if x > 0:
    print(x, 'is positive')
elif x == 0:
    print(x, 'is zero')
else:
    print(x, 'is negative')

5 is positive


In [48]:
x = 0                                #experiment with different values of x to make sure it works
if x > 0:
    print(x, 'is positive')
elif x == 0:
    print(x, 'is zero')
else:
    print(x, 'is negative')

0 is zero


In [49]:
x = -5                                #experiment with different values of x to make sure it works
if x > 0:
    print(x, 'is positive')
elif x == 0:
    print(x, 'is zero')
else:
    print(x, 'is negative')

-5 is negative
